-- ============================================================
-- S M Shahid Shah Webinar — Detailed Engagement Analytics
-- Run once in Supabase SQL Editor after the main webinar setup.
-- Tracks clicks, section views, scroll milestones and key actions.
-- ============================================================

create table if not exists public.webinar_engagement_events (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  session_id uuid not null,
  participant_email text,
  participant_name text,
  event_type text not null,
  target_type text,
  target_label text,
  target_url text,
  section_id text,
  scroll_percent smallint check (scroll_percent between 0 and 100),
  device_type text not null default 'desktop' check (device_type in ('mobile','tablet','desktop')),
  path text not null default '/',
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists webinar_engagement_occurred_at_idx
  on public.webinar_engagement_events (occurred_at desc);
create index if not exists webinar_engagement_visitor_id_idx
  on public.webinar_engagement_events (visitor_id);
create index if not exists webinar_engagement_email_idx
  on public.webinar_engagement_events (lower(participant_email));
create index if not exists webinar_engagement_event_type_idx
  on public.webinar_engagement_events (event_type);

alter table public.webinar_engagement_events enable row level security;

drop policy if exists "Webinar admins read engagement events" on public.webinar_engagement_events;
create policy "Webinar admins read engagement events"
on public.webinar_engagement_events
for select to authenticated
using (public.is_webinar_admin());

create or replace function public.track_webinar_engagement(
  p_visitor_id uuid,
  p_session_id uuid,
  p_participant_email text default null,
  p_participant_name text default null,
  p_event_type text default 'interaction',
  p_target_type text default null,
  p_target_label text default null,
  p_target_url text default null,
  p_section_id text default null,
  p_scroll_percent integer default null,
  p_device_type text default 'desktop',
  p_path text default '/',
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Once a visitor identifies through seat reservation or registered-email access,
  -- attach the same identity to their earlier anonymous events on this browser.
  if nullif(trim(p_participant_email), '') is not null then
    update public.webinar_engagement_events
    set participant_email = left(lower(trim(p_participant_email)), 320),
        participant_name = coalesce(left(nullif(trim(p_participant_name), ''), 160), participant_name)
    where visitor_id = p_visitor_id
      and participant_email is null;
  end if;

  insert into public.webinar_engagement_events (
    visitor_id,
    session_id,
    participant_email,
    participant_name,
    event_type,
    target_type,
    target_label,
    target_url,
    section_id,
    scroll_percent,
    device_type,
    path,
    metadata
  ) values (
    p_visitor_id,
    p_session_id,
    left(nullif(lower(trim(p_participant_email)), ''), 320),
    left(nullif(trim(p_participant_name), ''), 160),
    left(coalesce(nullif(trim(p_event_type), ''), 'interaction'), 60),
    left(nullif(trim(p_target_type), ''), 60),
    left(nullif(trim(p_target_label), ''), 240),
    left(nullif(trim(p_target_url), ''), 800),
    left(nullif(trim(p_section_id), ''), 100),
    case when p_scroll_percent is null then null else greatest(0, least(100, p_scroll_percent)) end,
    case when p_device_type in ('mobile','tablet','desktop') then p_device_type else 'desktop' end,
    left(coalesce(nullif(trim(p_path), ''), '/'), 300),
    coalesce(p_metadata, '{}'::jsonb)
  );
end;
$$;

create or replace function public.get_webinar_engagement_stats()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result jsonb;
begin
  if not public.is_webinar_admin() then
    raise exception 'Not authorized';
  end if;

  select jsonb_build_object(
    'total_events', count(*),
    'unique_visitors', count(distinct visitor_id),
    'identified_visitors', count(distinct lower(participant_email)) filter (where participant_email is not null),
    'click_events', count(*) filter (where event_type in ('social_click','video_click','link_click','navigation_click','button_click')),
    'scroll_events', count(*) filter (where event_type = 'scroll_milestone'),
    'section_views', count(*) filter (where event_type = 'section_view'),
    'form_starts', count(*) filter (where event_type = 'form_start'),
    'registration_events', count(*) filter (where event_type = 'registration_success'),
    'review_opens', count(*) filter (where event_type = 'review_open'),
    'review_submissions', count(*) filter (where event_type = 'review_submit')
  ) into v_result
  from public.webinar_engagement_events;

  v_result := v_result || jsonb_build_object(
    'top_targets', coalesce((
      select jsonb_agg(
        jsonb_build_object('label', label, 'url', url, 'events', events)
        order by events desc
      )
      from (
        select
          coalesce(nullif(target_label, ''), nullif(target_url, ''), 'Unknown target') as label,
          max(target_url) as url,
          count(*) as events
        from public.webinar_engagement_events
        where event_type in ('social_click','video_click','link_click','navigation_click','button_click')
        group by 1
        order by events desc
        limit 10
      ) ranked
    ), '[]'::jsonb),
    'event_types', coalesce((
      select jsonb_agg(
        jsonb_build_object('event_type', event_type, 'events', events)
        order by events desc
      )
      from (
        select event_type, count(*) as events
        from public.webinar_engagement_events
        group by event_type
        order by events desc
        limit 12
      ) ranked
    ), '[]'::jsonb)
  );

  return v_result;
end;
$$;

revoke all on public.webinar_engagement_events from anon, authenticated;
grant select on public.webinar_engagement_events to authenticated;

revoke all on function public.track_webinar_engagement(uuid, uuid, text, text, text, text, text, text, text, integer, text, text, jsonb) from public;
revoke all on function public.get_webinar_engagement_stats() from public;
grant execute on function public.track_webinar_engagement(uuid, uuid, text, text, text, text, text, text, text, integer, text, text, jsonb) to anon, authenticated;
grant execute on function public.get_webinar_engagement_stats() to authenticated;

-- Enable live INSERT notifications for the Engagement Details admin tab.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'webinar_engagement_events'
  ) then
    execute 'alter publication supabase_realtime add table public.webinar_engagement_events';
  end if;
end $$;

-- Privacy behavior:
-- 1. Visitors remain anonymous until they reserve a seat or verify a registered email.
-- 2. Passwords, form field values, message contents, IP addresses and precise location are not stored.
-- 3. Scroll is recorded only at 25%, 50%, 75%, 90% and 100% milestones to avoid excessive data.
