-- ============================================================
-- S M Shahid Shah Webinar — Visitor Analytics Upgrade
-- Run once in Supabase SQL Editor after the main setup SQL.
-- ============================================================

create table if not exists public.webinar_visits (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  session_id uuid not null,
  path text not null default '/',
  referrer text not null default 'Direct',
  device_type text not null default 'desktop' check (device_type in ('mobile','tablet','desktop')),
  browser_language text,
  screen_size text,
  visited_at timestamptz not null default now()
);

create index if not exists webinar_visits_visited_at_idx on public.webinar_visits (visited_at desc);
create index if not exists webinar_visits_visitor_id_idx on public.webinar_visits (visitor_id);
create index if not exists webinar_visits_device_type_idx on public.webinar_visits (device_type);

alter table public.webinar_visits enable row level security;

drop policy if exists "Webinar admins read visits" on public.webinar_visits;
create policy "Webinar admins read visits"
on public.webinar_visits
for select to authenticated
using (public.is_webinar_admin());

create or replace function public.track_webinar_visit(
  p_visitor_id uuid,
  p_session_id uuid,
  p_path text default '/',
  p_referrer text default 'Direct',
  p_device_type text default 'desktop',
  p_browser_language text default null,
  p_screen_size text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.webinar_visits (
    visitor_id, session_id, path, referrer, device_type,
    browser_language, screen_size
  ) values (
    p_visitor_id,
    p_session_id,
    left(coalesce(nullif(trim(p_path), ''), '/'), 300),
    left(coalesce(nullif(trim(p_referrer), ''), 'Direct'), 300),
    case when p_device_type in ('mobile','tablet','desktop') then p_device_type else 'desktop' end,
    left(nullif(trim(p_browser_language), ''), 30),
    left(nullif(trim(p_screen_size), ''), 30)
  );
end;
$$;

create or replace function public.get_webinar_visit_stats()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_today_start timestamptz := date_trunc('day', now() at time zone 'Asia/Karachi') at time zone 'Asia/Karachi';
  v_result jsonb;
begin
  if not public.is_webinar_admin() then
    raise exception 'Not authorized';
  end if;

  select jsonb_build_object(
    'total_visits', count(*),
    'unique_visitors', count(distinct visitor_id),
    'today_visits', count(*) filter (where visited_at >= v_today_start),
    'last_7_days', count(*) filter (where visited_at >= now() - interval '7 days'),
    'last_30_days', count(*) filter (where visited_at >= now() - interval '30 days'),
    'mobile_visits', count(*) filter (where device_type = 'mobile'),
    'tablet_visits', count(*) filter (where device_type = 'tablet'),
    'desktop_visits', count(*) filter (where device_type = 'desktop')
  ) into v_result
  from public.webinar_visits;

  v_result := v_result || jsonb_build_object(
    'top_referrers', coalesce((
      select jsonb_agg(jsonb_build_object('source', source, 'visits', visits) order by visits desc)
      from (
        select coalesce(nullif(referrer, ''), 'Direct') as source, count(*) as visits
        from public.webinar_visits
        group by 1
        order by visits desc
        limit 5
      ) ranked
    ), '[]'::jsonb)
  );

  return v_result;
end;
$$;

revoke all on public.webinar_visits from anon, authenticated;
grant select on public.webinar_visits to authenticated;

revoke all on function public.track_webinar_visit(uuid, uuid, text, text, text, text, text) from public;
revoke all on function public.get_webinar_visit_stats() from public;
grant execute on function public.track_webinar_visit(uuid, uuid, text, text, text, text, text) to anon, authenticated;
grant execute on function public.get_webinar_visit_stats() to authenticated;

-- Visitor IDs are browser-generated anonymous identifiers. No email, phone,
-- precise location or IP address is stored by this setup.

-- Enable live INSERT notifications for the admin Visitor Analytics tab.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'webinar_visits'
  ) then
    execute 'alter publication supabase_realtime add table public.webinar_visits';
  end if;
end $$;

